# Generated by Django 5.2.4 on 2025-07-26 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_stock_reorder_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='reorder_level',
            new_name='reorder_threshold',
        ),
    ]
